icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M, w:4) "

[[block]]
block = "temperature"
format = " $icon $max "
interval = 10
chip = "*-isa-*"

[[block]]
block = "battery"
format = " $icon  {$percentage $power.eng(w:4)} "
full_format = " $icon  Full "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%d/%m/%y %R') "
